blank_issues_enabled: false
contact_links:
  - name: Questions and community discussions
    url: https://github.com/orgs/mss-boot-io/discussions
    about: Ask usage questions and share ideas in GitHub Discussions.
